name: offline_ecommerce
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # for local database
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  sqlite3_flutter_libs: ^0.5.40
  path_provider: ^2.1.5
  path: ^1.9.1

  # for state management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # for making network requests
  dio: ^5.9.0
  retrofit: ^4.9.1
  json_annotation: ^4.9.0

  # for checking internet connectivity
  connectivity_plus: ^7.0.0

  # for dependency injection
  get_it: ^9.1.1
  injectable: ^2.7.0


  shared_preferences: ^2.5.3
  intl: ^0.20.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # code generation tools
  build_runner: ^2.10.4
  drift_dev: ^2.29.0
  retrofit_generator: ^10.2.0
  json_serializable: ^6.11.2
  


flutter:

  uses-material-design: true

